# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DSTWorkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_results_detail', models.CharField(max_length=200)),
                ('no_pathology', models.BooleanField()),
                ('pathology_report_date', models.DateTimeField(verbose_name=b'pathology report date')),
                ('receptor_test', models.CharField(choices=[(b'Estrogen receptor', ((b'er+', b'ER+'), (b'er-', b'ER-'), (b'not determined', b'not determined'))), (b'Progesterone receptor', ((b'pr+', b'PR+'), (b'pr-', b'PR-'), (b'not determined', b'not determined'))), (b'HER2 IHC', ((b'her2 ihc+', b'HER2 IHC+'), (b'her2 ihc-', b'HER2 IHC-'), (b'not determined', b'not determined'))), (b'HER2 FISH', ((b'her2 fish+', b'HER2 FISH+'), (b'her2 fish-', b'HER2 FISH-'), (b'not determined', b'not determined')))], max_length=20)),
                ('imaging_assessment', models.CharField(max_length=1000)),
                ('recorded_date', models.DateTimeField(verbose_name=b'date recorded')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('study_date', models.DateTimeField(verbose_name=b'study date')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_diagnosis', models.BooleanField()),
                ('history_suggests_cancer', models.NullBooleanField()),
                ('widely_metastatic_cancer', models.BooleanField()),
                ('diagnosable_at_location', models.BooleanField()),
                ('treatable_at_location', models.NullBooleanField()),
                ('recorded_date', models.DateTimeField(verbose_name=b'date recorded')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Institution'),
        ),
        migrations.AddField(
            model_name='dstworkup',
            name='follow_up_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Reason'),
        ),
        migrations.AddField(
            model_name='dstworkup',
            name='imaging_studies',
            field=models.ManyToManyField(to='canreg.ImagingStudy'),
        ),
        migrations.AddField(
            model_name='dstworkup',
            name='pathology_diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Diagnosis'),
        ),
        migrations.AddField(
            model_name='dstworkup',
            name='pathology_report_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Institution'),
        ),
    ]
