# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DSTWorkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pathology', models.BooleanField()),
                ('pathology_report_date', models.DateTimeField(blank=True, verbose_name=b'pathology report date')),
                ('imaging_assessment', models.CharField(max_length=1000)),
                ('recorded_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DSTWorkupDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Diagnosis')),
                ('dst_workup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.DSTWorkup')),
            ],
        ),
        migrations.CreateModel(
            name='DSTWorkupImagingStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateTimeField(verbose_name=b'study date')),
                ('dst_workup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.DSTWorkup')),
            ],
        ),
        migrations.CreateModel(
            name='DSTWorkupInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('dst_workup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.DSTWorkup')),
            ],
        ),
        migrations.CreateModel(
            name='DSTWorkupReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('dst_workup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.DSTWorkup')),
            ],
        ),
        migrations.CreateModel(
            name='DSTWorkupReceptorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.NullBooleanField()),
                ('dst_workup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.DSTWorkup')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PatientWorkflowHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_state', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_diagnosis', models.BooleanField()),
                ('history_suggests_cancer', models.NullBooleanField()),
                ('widely_metastatic_cancer', models.BooleanField()),
                ('diagnosable_at_location', models.BooleanField()),
                ('treatable_at_location', models.NullBooleanField()),
                ('recorded_date', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='dstworkupreceptorstatus',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Receptor'),
        ),
        migrations.AddField(
            model_name='dstworkupreason',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Reason'),
        ),
        migrations.AddField(
            model_name='dstworkupinstitution',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Institution'),
        ),
        migrations.AddField(
            model_name='dstworkupimagingstudy',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Institution'),
        ),
        migrations.AddField(
            model_name='dstworkup',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Patient'),
        ),
    ]
