# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dstworkupdiagnosis',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='dstworkupinstitution',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='dstworkupreason',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
