# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='year_of_birth',
            field=models.IntegerField(default=1990),
            preserve_default=False,
        ),
    ]
