# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canreg', '0003_auto_20170726_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dstworkup',
            name='pathology_report_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
