# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyBoneDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnatomyLocationDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnatomySiteDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Biopsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologist_facility', models.CharField(blank=True, max_length=200)),
                ('procedure_date', models.DateTimeField()),
                ('pathologist_name', models.CharField(blank=True, max_length=200)),
                ('pathology_report_date', models.DateTimeField()),
                ('lvi', models.CharField(choices=[('LVI+', 'LVI+'), ('LVI-', 'LVI-'), ('ND', 'Not Determined')], default='ND', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='BiopsyGradeDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='BiopsyHistologyDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BiopsyReceptorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(default=False)),
                ('biopsy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.Biopsy')),
            ],
        ),
        migrations.CreateModel(
            name='BiopsySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('R', 'Right'), ('L', 'Left')], default='', max_length=1)),
                ('description', models.CharField(max_length=200)),
                ('biopsy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.Biopsy')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.AnatomyLocationDict')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.AnatomySiteDict')),
            ],
        ),
        migrations.CreateModel(
            name='BiopsyStatusDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BiopsyTypeDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='NoBiopsyReasonDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateTimeField(auto_now=True)),
                ('biopsy_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.BiopsyStatusDict')),
                ('no_biopsy_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.NoBiopsyReasonDict')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptorStrengthDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptorTestDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledBiopsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_procedure_date', models.DateTimeField()),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.InstitutionDict')),
                ('pathology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.Pathology')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.BiopsyTypeDict')),
            ],
        ),
        migrations.AddField(
            model_name='biopsyreceptorstatus',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.Receptor'),
        ),
        migrations.AddField(
            model_name='biopsyreceptorstatus',
            name='strength',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.ReceptorStrengthDict'),
        ),
        migrations.AddField(
            model_name='biopsyreceptorstatus',
            name='test_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.ReceptorTestDict'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.BiopsyGradeDict'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='histology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.BiopsyHistologyDict'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='pathology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.Patient'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='procedure_hospital_or_clinic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canreg.InstitutionDict'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.BiopsyTypeDict'),
        ),
    ]
