# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsy',
            name='pathologist_facility',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
