# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0005_auto_20170809_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='no_biopsy_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.NoBiopsyReasonDict'),
        ),
    ]
