# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0007_auto_20170809_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsyreceptorstatus',
            name='strength',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.ReceptorStrengthDict'),
        ),
        migrations.AlterField(
            model_name='biopsyreceptorstatus',
            name='test_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.ReceptorTestDict'),
        ),
    ]
