# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0008_auto_20170809_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsyreceptorstatus',
            name='is_positive',
            field=models.NullBooleanField(),
        ),
    ]
