# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0009_auto_20170810_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsysite',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biopsysite',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.AnatomyLocationDict'),
        ),
        migrations.AlterField(
            model_name='biopsysite',
            name='side',
            field=models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left')], default='', max_length=1, null=True),
        ),
    ]
